name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Needs Checking]
assignees:
  - natr566
body:
- type: markdown
  attributes:
    value: "CustomUniverse (free) is a dependency for CustomItems. **Your server will automatically shut down if you try to start it up without CustomUniverse installed.** This is to prevent any damage that might occur if people unknowingly start their server with CustomItems disabled.

Download CustomUniverse for free from Polymart from https://polymart.org/r/customuniverse.1220"
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Explain your Bug / Issue
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: input
  attributes:
    label: Minecraft Version
    description: Use this box to tell us your minecraft version.
  validations:
    required: true
- type: input
  attributes:
    label: Plugin Version
    description: Use this box to tell us the version of the plugin your are using "/cui version".
  validations:
    required: true
- type: input
  attributes:
    label: Server log.
    description: Upload your your server log to either https://paste.gg or https://gist.github.com, save and then paste the link in this box.
    placeholder: "Example: https://paste.gg/p/anonymous/109dd6a10a734a3aa430d5a351ea5210"
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
